### ISSUE TITLE
Page add suggestion

### ISSUE THREAD

**Issue by ihougland** [kthornbloom/JACKRABBIT-CMS#59]
Currently, there is no ability to add a sub page to a page unless there is already a sub page present. MY workaround for this has been to add the page in a section that allows it, then drag it underneath the page that it actually needs to go under. It would be nice to have the ability to add a sub page to ANY page, however, the sidebar would get very unwieldy with "add page" text under every single page. Maybe a + to the side instead?

**Comment by kthornbloom** [comment]
- I like the idea of just using a + symbol
- I don't think we can add what you're talking about though. It would be way too many symbols, and there wouldn't be a great way to differentiate between adding as a sub-page, or adding as top-level.
- I think the current method works pretty well since once you create a sub-menu, you can then add directly to it.
